# Generated by Django 3.0.8 on 2020-07-30 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=3000)),
                ('is_published', models.BooleanField()),
                ('author', models.ForeignKey(default='Anonymous', on_delete=models.SET('Anonymous'), related_name='post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('is_published', models.BooleanField()),
                ('author', models.ForeignKey(default='Anonymous', on_delete=models.SET('Anonymous'), related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(default='Post_Not_available', on_delete=models.SET('Post_Not_available'), related_name='commented_post', to='feed.Post')),
            ],
        ),
    ]
