# Generated by Django 3.0.8 on 2020-07-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
